#lang racket

(require "interpreter.rkt")
(require rackunit)

;(check-equal? (interpret "tests/p4t1.bad" "A") 15)
;(check-equal? (interpret "tests/p4t2.bad" "A") 12)
;(check-equal? (interpret "tests/p4t3.bad" "A") 125)
;(check-equal? (interpret "tests/p4t4.bad" "A") 36)
;(check-equal? (interpret "tests/p4t5.bad" "A") 54)
;(check-equal? (interpret "tests/p4t6.bad" "A") 110)
;(check-equal? (interpret "tests/p4t7.bad" "C") 26)
;(check-equal? (interpret "tests/p4t8.bad" "Square") 117)
;(check-equal? (interpret "tests/p4t9.bad" "Square") 32)
;(check-equal? (interpret "tests/p4t10.bad" "List") 15)
;(check-equal? (interpret "tests/p4t11.bad" "List") 123456)
;(check-equal? (interpret "tests/p4t12.bad" "List") 5285)
;(check-equal? (interpret "tests/p4t13.bad" "C") -716)
;(check-equal? (interpret "tests/p4t21.bad" "A") 530)
;(check-equal? (interpret "tests/p4t22.bad" "B") 66)
;(check-equal? (interpret "tests/p4t23.bad" "A") 1026)
;(check-equal? (interpret "tests/p4t24.bad" "A") 2045)
