name: Racket Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    container:
      image: racket/racket-ci:latest
      options: --init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Racket environment
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.11'

      - name: Run unit tests
        run: raco test tests.rkt

      - name: Check test results and prevent push on failure
        if: ${{ failure() }}
        run: echo "Tests failed. Changes cannot be pushed to main." && exit 1
