name: Racket Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Racket
        uses: nau/gh-actions-racket@v1
        with:
          version: '8.11.1' # Adjust the Racket version as needed

      - name: Run unit tests
        run: raco test path/to/tests/*.rkt

      - name: Check test results and prevent push on failure
        if: ${{ failure() }}
        run: echo "Tests failed. Changes cannot be pushed to main." && exit 1
